# Generated by Django 5.2.8 on 2026-07-01 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushdevice',
            name='endpoint',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='webpushdevice',
            unique_together={('user', 'endpoint')},
        ),
    ]
