# Generated by Django 5.2.13 on 2026-06-12 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('login_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PortalScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('running', 'running'), ('success', 'success'), ('needs_login', 'needs-login'), ('failed', 'failed')], default='running', max_length=16)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='portals.portal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_scrape_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_state_ciphertext', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_login', 'Needs login'), ('expired', 'Expired')], default='needs_login', max_length=16)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='portals.portal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'portal')},
            },
        ),
    ]
