# Generated by Django 5.2.13 on 2026-05-19 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('signup_bonus', 'Signup bonus'), ('tailor_resume', 'Tailored a resume'), ('cover_letter', 'Drafted a cover letter'), ('autonomous_apply', 'Autonomous apply'), ('mock_interview', 'Mock interview'), ('top_up', 'Manual top-up'), ('stripe_purchase', 'Stripe purchase'), ('refund', 'Refund')], max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=128)),
                ('subscription_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='inactive', max_length=32)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
