# Generated by Django 5.2.13 on 2026-05-19 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV import'), ('google', 'Google Contacts'), ('profile_url', 'User-provided profile URL'), ('public_page', 'Public page')], default='manual', max_length=32)),
                ('seniority', models.CharField(blank=True, max_length=64)),
                ('relationship_strength', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='jobs.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActionQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_queue_items', to='jobs.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_queue_items', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_queue_items', to='networking.contact')),
            ],
            options={
                'ordering': ['status', 'due_at', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('linkedin', 'LinkedIn'), ('x', 'X / Twitter'), ('referral_form', 'Referral form'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('draft_body', models.TextField()),
                ('approved_body', models.TextField(blank=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('approved', 'Approved'), ('sent', 'Sent'), ('replied', 'Replied'), ('follow_up_due', 'Follow-up due'), ('closed', 'Closed')], default='drafted', max_length=32)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_messages', to='networking.contact')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_messages', to='jobs.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('contacted', 'Contacted'), ('referred', 'Referred'), ('declined', 'Declined'), ('closed', 'Closed')], default='suggested', max_length=32)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_opportunities', to='networking.contact')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_opportunities', to='jobs.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('send_outreach', 'Send outreach'), ('submit_application', 'Submit application'), ('use_credentials', 'Use credentials')], max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.PositiveBigIntegerField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('approval_token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user', 'name'], name='networking__user_id_a4f2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user', 'email'], name='networking__user_id_4bcc60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referralopportunity',
            unique_together={('user', 'job', 'contact')},
        ),
    ]
