# Generated by Django 5.2.13 on 2026-05-27 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('networking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('acquired', 'Acquired by'), ('parent', 'Parent of'), ('subsidiary', 'Subsidiary of'), ('spinoff', 'Spinoff from'), ('competitor', 'Competitor of'), ('partner', 'Partner of')], max_length=32)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_company_rels', to='jobs.company')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_company_rels', to='jobs.company')),
            ],
            options={
                'unique_together': {('from_company', 'to_company', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='ContactEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV import'), ('google', 'Google Contacts'), ('profile_url', 'User-provided profile URL'), ('public_page', 'Public page')], default='manual', max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='jobs.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='networking.contact')),
            ],
            options={
                'ordering': ['-is_current', '-started_at'],
                'indexes': [models.Index(fields=['contact', '-started_at'], name='networking__contact_e59a9e_idx'), models.Index(fields=['company', 'is_current'], name='networking__company_86b77c_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'company', 'title', 'started_at'), name='uniq_contact_employment')],
            },
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('colleague', 'Colleague (overlapping employment)'), ('manager', 'Manager / report-to'), ('report', 'Direct report'), ('reference', 'Professional reference'), ('mutual', 'Mutual connection'), ('classmate', 'Classmate'), ('friend', 'Friend')], max_length=32)),
                ('strength', models.PositiveSmallIntegerField(default=3)),
                ('inferred', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='networking.contact')),
                ('to_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='networking.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'from_contact'], name='networking__user_id_9e9275_idx'), models.Index(fields=['user', 'to_contact'], name='networking__user_id_e1cde0_idx')],
                'unique_together': {('user', 'from_contact', 'to_contact', 'kind')},
            },
        ),
    ]
