# Generated by Django 5.2.13 on 2026-06-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscore',
            name='explanation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
