# Generated by Django 5.2.13 on 2026-05-19 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('onboarding', 'Onboarding'), ('general', 'General'), ('tailoring', 'Tailoring'), ('autonomous_apply', 'Autonomous Apply')], default='general', max_length=32)),
                ('status', models.CharField(choices=[('active', 'active'), ('paused_hitl', 'paused-hitl'), ('done', 'done'), ('failed', 'failed')], default='active', max_length=32)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('pending_approval', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('tool', 'tool'), ('system', 'system')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('tool_name', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.agentsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
