# Generated by Django 5.2.13 on 2026-05-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('aggregator', 'Aggregator API'), ('ats_public', 'Public ATS board'), ('scraper', 'Custom scraper'), ('email_forward', 'Email forward'), ('web_search', 'Web search'), ('cli_delegate', 'CLI delegate'), ('linkedin', 'LinkedIn (best-effort)')], max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ats_type', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('workday', 'Workday'), ('smartrecruiters', 'SmartRecruiters'), ('other', 'Other')], default='other', max_length=32)),
                ('careers_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('name', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255)),
                ('remote', models.BooleanField(default=False)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=8)),
                ('apply_url', models.URLField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.source')),
            ],
            options={
                'ordering': ['-posted_at', '-created_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
